version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: go run service.go
    volumes:
      - ./wxapi:/go/src/wxapi
    ports:
      - "8000:8000"
    depends_on:
      - db
